---

- hosts: localhost
  gather_facts: yes

  tasks:

  - name: Update the apt package index
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes

  - name: Install packages for apt add repository over HTTPS
    become: yes
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - mailutils
      - postfix
    tags: "init postfix"

  - name: Install packages for apt add repository over HTTPS
    become: yes
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: absent
      update_cache: yes
    vars:
      packagesdep:
      - mailutils
      - postfix
    tags: "drop postfix"
